name: Sync Image to Aliyun  Example
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Git pull
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1
 
    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        logout: false
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         #skopeo copy hub.docker.com/r/netflixoss/eureka:latest docker://registry.cn-hangzhou.aliyuncs.com/guigusuqi/eureka:latest
         #skopeo copy docker://docker.io/zookeeper:3.7 docker://registry.cn-hangzhou.aliyuncs.com/guigusuqi/zookeeper:latest
         skopeo copy docker://docker.io/kafka:3.7.1 docker://registry.cn-hangzhou.aliyuncs.com/guigusuqi/kafka:latest
         #skopeo copy docker://docker.io/zookeeper:3.7 docker://registry.cn-hangzhou.aliyuncs.com/guigusuqi/nginx:latest
      # 使用 skopeo 工具将镜像同步到阿里云个人仓库中，使用时请自行源和目标修改仓库名称和镜像名称
